version: "3"

services:
  frontend:
    container_name: falu_fe
    hostname: falu_fe
    build: ./frontend/
    depends_on:
      - backend
      - nginx
    restart: on-failure
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    networks:
      falu_net:
        ipv4_address: 10.10.13.2

  nginx:
    image: nginx:alpine
    container_name: falu_nginx
    hostname: falu_nginx
    restart: on-failure
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      falu_net:
        ipv4_address: 10.10.13.3

  cron:
    container_name: falu_cron
    hostname: falu_cron
    build: ./cron/
    restart: on-failure
    depends_on:
      - backend
    networks:
      falu_net:
        ipv4_address: 10.10.13.6

  backend:
    container_name: falu_be
    hostname: falu_be
    build: ./backend/
    depends_on:
      - database
    restart: on-failure
    environment:
      - FLASK_DEBUG=1
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    networks:
      falu_net:
        ipv4_address: 10.10.13.4

  database:
    container_name: falu_db
    build: ./db/
    restart: on-failure
    ports:
     - 5432:5432
    networks:
      falu_net:
        ipv4_address: 10.10.13.5
    env_file:
      - .env
    volumes:
      - ./db/data/:/var/lib/postgresql/data/

networks:
  falu_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.13.0/24
